// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import "dotenv/config";
import { defineConfig } from "prisma/config";

export default defineConfig({
  schema: "prisma/schema.prisma",
  migrations: {
    path: "prisma/migrations",
    seed: "ts-node --compiler-options {\"module\":\"CommonJS\"} prisma/seed.ts",
  },
  datasource: {
    url: process.env["DATABASE_URL"],
    // Note: Shadow database disabled for pgvector extension compatibility
    // Use PRISMA_DISABLE_SHADOW_DATABASE=1 environment variable or manual migration
    // For production: Use prisma migrate deploy instead of migrate dev
  },
});
